import{Canvas,useThree}from'@react-three/fiber';import{Environment,Grid,OrbitControls,useGLTF}from'@react-three/drei';import{Suspense,useEffect,useRef,useState}from'react';import*as THREE from'three';import{Download,FolderOpen,HelpCircle,Image as ImageIcon,RotateCcw,Trash2}from'lucide-react';import{db}from'./db';import{useStudio,type ExportFormat}from'./store';

type Loaded={name:string;url:string;dbId?:number};let capture:((w:number,h:number,m:string,q:number)=>Promise<Blob>)|null=null;
function Model({item}:{item:Loaded}){const g=useGLTF(item.url);const ref=useRef<THREE.Group>(null);useEffect(()=>{if(!ref.current)return;const box=new THREE.Box3().setFromObject(ref.current),s=box.getSize(new THREE.Vector3()),c=box.getCenter(new THREE.Vector3()),k=3/Math.max(s.x,s.y,s.z,0.001);ref.current.scale.setScalar(k);ref.current.position.set(-c.x*k,-box.min.y*k,-c.z*k)},[g]);return <primitive ref={ref} object={g.scene.clone(true)}/>;}
function Scene({models}:{models:Loaded[]}){const s=useStudio(),{gl,scene,camera}=useThree();useEffect(()=>{capture=async(w,h,m,q)=>{const old=new THREE.Vector2();gl.getSize(old);const ratio=gl.getPixelRatio();gl.setPixelRatio(1);gl.setSize(w,h,false);camera.aspect=w/h;(camera as THREE.PerspectiveCamera).updateProjectionMatrix();gl.render(scene,camera);const blob=await new Promise<Blob>((ok,no)=>gl.domElement.toBlob(b=>b?ok(b):no(new Error('Görsel oluşturulamadı')),m,q));gl.setPixelRatio(ratio);gl.setSize(old.x,old.y,false);camera.aspect=old.x/old.y;(camera as THREE.PerspectiveCamera).updateProjectionMatrix();return blob};return()=>{capture=null}},[gl,scene,camera]);return <><color attach="background" args={[s.bg]}/><ambientLight intensity={s.light*.45}/><directionalLight position={[4,7,5]} intensity={s.light} castShadow/><Suspense fallback={null}>{models.map((m,i)=><Model key={m.url+i} item={m}/>)}</Suspense><Grid infiniteGrid fadeDistance={25} cellSize={.5} sectionSize={2}/><OrbitControls makeDefault autoRotate={s.autoRotate} autoRotateSpeed={1.4} enableDamping/></>}

const steps=['Model yükle','Parmağınla döndür ve yakınlaştır','Işık ve stüdyoyu ayarla','Kamera açını seç','Görsel üret','Kalite / KB ayarla ve indir'];
async function fitTarget(w:number,h:number,m:ExportFormat,target:number){if(!capture)throw Error('Sahne hazır değil');if(m==='image/png')return capture(w,h,m,1);let lo=.05,hi=1,b=await capture(w,h,m,.92);for(let i=0;i<8;i++){const q=(lo+hi)/2,x=await capture(w,h,m,q);b=x;if(x.size/1024>target)hi=q;else lo=q}return b}
function App(){const s=useStudio(),[models,setModels]=useState<Loaded[]>([]),[tab,setTab]=useState('Sahne'),[busy,setBusy]=useState(false),[tip,setTip]=useState(0),[gallery,setGallery]=useState<{id?:number;name:string;blob:Blob}[]>([]);
useEffect(()=>{(async()=>{const ms=await db.models.toArray();setModels(ms.map(x=>({name:x.name,url:URL.createObjectURL(x.blob),dbId:x.id})));setGallery(await db.gallery.orderBy('created').reverse().limit(50).toArray())})()},[]);
const add=async(file:File)=>{if(!/\.(glb|gltf)$/i.test(file.name)){alert('Şimdilik GLB ve GLTF destekleniyor.');return}const id=await db.models.add({name:file.name,blob:file,updated:Date.now()});setModels(x=>[...x,{name:file.name,url:URL.createObjectURL(file),dbId:id}])};
const sample=()=>setModels(x=>[...x,{name:'Damaged Helmet',url:'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb'}]);
const remove=async(i:number)=>{const m=models[i];if(m.dbId)await db.models.delete(m.dbId);URL.revokeObjectURL(m.url);setModels(x=>x.filter((_,n)=>n!==i))};
const produce=async()=>{try{setBusy(true);const b=await fitTarget(s.width,s.height,s.format,s.targetKB);const ext=s.format.split('/')[1].replace('jpeg','jpg'),name=`3D-Nexus-${s.projectName.replace(/\s+/g,'-')}-${new Date().toISOString().slice(0,10)}.${ext}`;const id=await db.gallery.add({name,blob:b,created:Date.now()});setGallery(x=>[{id,name,blob:b},...x].slice(0,50));download(b,name)}catch(e){alert(e instanceof Error?e.message:'Üretim başarısız')}finally{setBusy(false)}};
const download=(b:Blob,n:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
return <main><header><b>◈ 3D Nexus</b><input value={s.projectName} onChange={e=>s.set({projectName:e.target.value})}/><span className="saved">● Kaydedildi</span><button onClick={()=>{s.set({tutorialDone:false});setTip(0)}}><HelpCircle/> Yardım</button></header>
<section className="workspace"><aside className="panel left"><h3>Kütüphane</h3><label className="primary"><FolderOpen/> Model yükle<input hidden type="file" accept=".glb,.gltf" onChange={e=>e.target.files?.[0]&&add(e.target.files[0])}/></label><button onClick={sample}>Örnek model yükle</button>{models.map((m,i)=><div className="model" key={m.url}>{m.name}<button onClick={()=>remove(i)} aria-label="Sil"><Trash2/></button></div>)}</aside>
<div className="stage">{models.length===0&&<div className="empty"><b>3D sahnen hazır</b><span>Model yükle veya örnekle başla</span><button className="primary" onClick={sample}>Örnek model yükle</button></div>}<Canvas shadows gl={{preserveDrawingBuffer:true,antialias:true}} camera={{position:[4,3,5],fov:s.fov}}><Scene models={models}/></Canvas></div>
<aside className="panel right"><h3>Stüdyo</h3><label>Arka plan<input type="color" value={s.bg} onChange={e=>s.set({bg:e.target.value})}/></label><label>Işık {s.light.toFixed(1)}<input type="range" min=".2" max="6" step=".1" value={s.light} onChange={e=>s.set({light:+e.target.value})}/></label><label>FOV {s.fov}°<input type="range" min="20" max="90" value={s.fov} onChange={e=>s.set({fov:+e.target.value})}/></label><button onClick={()=>s.set({autoRotate:!s.autoRotate})}><RotateCcw/> Otomatik döndür: {s.autoRotate?'Açık':'Kapalı'}</button><hr/><h3>Görsel Üret</h3><select value={s.format} onChange={e=>s.set({format:e.target.value as ExportFormat})}><option value="image/png">PNG</option><option value="image/jpeg">JPG</option><option value="image/webp">WebP</option></select><div className="pair"><input type="number" value={s.width} onChange={e=>s.set({width:+e.target.value})}/><span>×</span><input type="number" value={s.height} onChange={e=>s.set({height:+e.target.value})}/></div><label>Kalite %{s.quality}<input type="range" min="1" max="100" value={s.quality} onChange={e=>s.set({quality:+e.target.value})}/></label>{s.format!=='image/png'&&<label>Hedef KB<input type="number" value={s.targetKB} onChange={e=>s.set({targetKB:+e.target.value})}/></label>}<button className="primary" disabled={busy} onClick={produce}><ImageIcon/>{busy?'Üretiliyor…':'Görsel Üret'}</button></aside></section>
<nav>{['Sahne','Kütüphane','Üret','Galeri'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
{tab==='Galeri'&&<div className="drawer"><h2>Galeri</h2>{gallery.length===0?'Henüz görsel yok.':gallery.map((g,i)=><button key={g.id??i} onClick={()=>download(g.blob,g.name)}><Download/> {g.name} · {Math.round(g.blob.size/1024)} KB</button>)}</div>}
{!s.tutorialDone&&<div className="tour"><small>ADIM {tip+1}/6</small><h2>{steps[tip]}</h2><p>{tip===0?'Telefondan GLB/GLTF seçebilir veya örnek modelle başlayabilirsin.':'Ekrandaki araçları deneyerek sahneni hazırlayabilirsin.'}</p><div>{tip>0&&<button onClick={()=>setTip(tip-1)}>Geri</button>}<button className="primary" onClick={()=>tip<5?setTip(tip+1):s.set({tutorialDone:true})}>{tip<5?'İleri':'Başla'}</button></div></div>}</main>}
export default App;