name: EAS Android APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm install -g eas-cli
      - run: eas whoami
      - run: eas init --account asilturk07 --non-interactive
      - run: eas build --platform android --profile preview --non-interactive --no-wait
